CREATE TABLE tb_user (
	ID int NOT NULL,
	USER_NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	FULL_NAME VARCHAR(255),
	ADDRESS VARCHAR(500),
	STATUS VARCHAR(500),
	ROLE VARCHAR(500) ,
	PRIMARY KEY (ID)
)